% --- DATA PROCESSOR ---
input_path = 'long_input.txt';
output_path = 'long_expected.txt';
initial_state = [1 0 0 1 0 1 0 1 0 0 0 0 0 0 0];

% 1. Load data generated by generator.m
fid_in = fopen(input_path, 'r');
if fid_in == -1, error('Run generator.m first!'); end
input_data = fscanf(fid_in, '%d')'; % Read and transpose to row
fclose(fid_in);

% 2. Process with Scrambler
scrambled_output = scramble_fxn_with_print(input_data, initial_state);
%disp(scrambled_output);
% 3. Save Golden Reference for Verilog comparison
fid_out = fopen(output_path, 'w');
fprintf(fid_out, '%d\n', scrambled_output);
fclose(fid_out);

disp(['SUCCESS: Golden reference saved to: ', output_path]);

% --- SCRAMBLER FUNCTION ---
function output = scramble_fxn_with_print(input_data, initial_state)
    n = length(input_data);
    output = zeros(1, n);
    state = initial_state;
    
    fprintf('\n--- STARTING 1000 BIT MONITOR ---\n');
    fprintf('%-8s | %-5s | %-6s | %-s\n', 'Index', 'In', 'Out', 'Register State');
    fprintf('------------------------------------------------------------\n');

    for i = 1:n
        % Reset logic: Flush to initial_state every 10 bits
        if i > 1 && mod(i-1, 20) == 0
            state = initial_state;
        end
        
        % Scrambling logic: x^14 + x^15 + 1
        fb = mod(state(14) + state(15), 2);
        output(i) = mod(input_data(i) + fb, 2);
        
        % Print first 1000 bits
        if i <= 1000
            % Convert state vector to a readable string for printing
            state_str = sprintf('%d', state); 
            fprintf('%-8d | %-5d | %-6d | %s\n', i, input_data(i), output(i), state_str);
        end

        % Update state (Shift Right)
        state = [fb, state(1:14)];
    end
end
